[theme]
base = "light"
primaryColor = "#A36A13"
backgroundColor = "#F7F8F5"
secondaryBackgroundColor = "#F0F3ED"
textColor = "#192C32"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 10
